#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib = []
n = 32

fib.append(0)
fib.append(1)
fib.append(2)

def next_fib(a,b):
        c = a + b
        return c

def sequence(N):
        for i in range(N):
                c = next_fib(fib[i+1], fib[i+2])
                fib.append(c)

sequence(n)

fib_two = []

for i in range(n+1):
        if fib[i] % 2 == 0:
                fib_two.append(fib[i])

x = sum(fib_two)


print("The sum of ", fib_two, "is ", x)
