# how many distinct terms are in the sequence generated by a**b for 2 <= a <= 100
# and 2 <= b <= 100 (removing repeats

terms = []

for a in range(2, 101):
    for b in range(2, 101):
        terms.append(a**b)

noRepeats = []

for i in terms:
    if i  not in noRepeats:
        noRepeats.append(i)

print(len(noRepeats))
